###create new report 
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Ford",
  "model": "Mustang",
  "price": 54000,
  "year": 2018,
  "lat": 40,
  "lng": 40,
  "milage": 5000
}


### get all reports 
GET http://localhost:3000/reports/all-reports?page=1&limit=3&sortBy=id:DESC'


### get one report 
GET http://localhost:3000/reports/1


###update report to approve or reject
PATCH http://localhost:3000/reports/5/approve


###update report to change any value
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
  "price": 45000,
  "milage": 10
}

### get estimate of a given car as a query 
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=2019&lat=40&lng=40&milage=5000
