###create new report 
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Ford",
  "model": "Mustang",
  "price": 54000,
  "year": 2016,
  "lat": 50,
  "lng": 45,
  "milage": 50000
}


### get all reports 
GET http://localhost:3000/reports


### get one report 
GET http://localhost:3000/reports/3


###update report to approve or reject
PATCH http://localhost:3000/reports/8/approve


###update report to change any value
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
  "price": 45000,
  "milage": 10
}

### get estimate of a given car as a query 
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=2019&lat=40&lng=40&milage=5000
